// <auto-generated />
using System;
using CrmPhotoVolta.Infrastructure.Data.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrmPhotoVolta.Infrastructure.Data.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505000000_AddMontantEstimeToLeads")]
    partial class AddMontantEstimeToLeads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrmPhotoVolta.Domain.App.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<bool>("BonusBudgetConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("BonusDecisionMaker")
                        .HasColumnType("boolean");

                    b.Property<bool>("BonusFinancingInterest")
                        .HasColumnType("boolean");

                    b.Property<bool>("BonusQuoteRequested")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<double?>("EstimatedKw")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Lvi")
                        .HasColumnType("double precision");

                    b.Property<double?>("MonthlyBillEur")
                        .HasColumnType("double precision");

                    b.Property<double?>("MontantEstimé")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<double?>("ScoreBreakdownActivity")
                        .HasColumnType("double precision");

                    b.Property<double?>("ScoreBreakdownIntention")
                        .HasColumnType("double precision");

                    b.Property<double?>("ScoreBreakdownInteraction")
                        .HasColumnType("double precision");

                    b.Property<double?>("ScoreBreakdownPenalties")
                        .HasColumnType("double precision");

                    b.Property<double?>("ScoreBreakdownPotential")
                        .HasColumnType("double precision");

                    b.Property<double?>("ScoreBreakdownSatisfaction")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sd")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("ScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("IX_Leads_SocietyId");

                    b.HasIndex("SocietyId", "Lvi")
                        .HasDatabaseName("IX_Leads_SocietyId_Lvi");

                    b.ToTable("Leads", "app");
                });

#pragma warning restore 612, 618
        }
    }
}
